use std::env;
use std::path::PathBuf;

fn main() {
    #[cfg(target_os = "linux")]
    println!("cargo:rustc-link-arg=-Wl,-rpath,$ORIGIN");

    #[cfg(target_os = "macos")]
    println!("cargo:rustc-link-arg=-Wl,-rpath,@loader_path");

    println!("cargo:rerun-if-changed=src/ffi.rs");

    #[cfg(feature = "generate-header")]
    generate_header();

    #[cfg(feature = "generate-bindings")]
    generate_bindings();
}

#[cfg(feature = "generate-header")]
fn generate_header() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    cbindgen::Builder::new()
        .with_crate(manifest_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("LIBMPV_WRAPPER_H")
        .with_header("/* automatically generated by cbindgen */")
        .generate()
        .expect("Failed to generate C bindings using cbindgen")
        .write_to_file("include/libmpv_wrapper.h");
}

#[cfg(feature = "generate-bindings")]
fn generate_bindings() {
    bindgen::Builder::default()
        .header("include/libmpv_wrapper.h")
        .dynamic_library_name("LibmpvWrapper")
        .allowlist_function("mpv_wrapper_.*")
        .allowlist_type("MpvHandle")
        .allowlist_type("EventCallback")
        .impl_debug(true)
        .wrap_unsafe_ops(true)
        .formatter(bindgen::Formatter::Prettyplease)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/libmpv_wrapper_bindings.rs")
        .expect("Unable to write bindings");
}
