[package]
name = "libmpv-wrapper"
version = "0.1.0"
edition = "2024"
description = "Wrapper for libmpv"
license = "LGPL-2.1"

[lib]
name = "mpv_wrapper"
crate-type = ["cdylib"]

[dependencies]
libmpv-sys = { path = "./libmpv-sys", default-features = false, features = [
  # "generate-bindings",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
log = "0.4"
scopeguard = "1"
indexmap = { version = "2", features = ["serde"] }
libloading = "0.8"

[features]
generate-bindings = ["libmpv-sys/generate-bindings"]

[build-dependencies]
cbindgen = "0.29"
bindgen = "0.72"

[package.metadata.cargo-post.dependencies]
zip = "6"

[profile.release]
lto = true
codegen-units = 1
